var TREE_ITEMS = [
	['AYUDA', 'ayuda.html',
		['INICIO', 'inicio.html'],
		['VER DATOS', 'verdatos.html'],
		['REGISTRAR ORDEN', 'regorden.html'],
		['ASIGNACIONES',    'asignaciones.html'],
		['ORDENES DE TRABAJO',    'ordtrabajo.html'],
		['GESTION - PRODAT ',null,
		['CONTRATOS', 'contratos.html'],
		['PROYECTOS',0,
		['SOLICITUD DE PROYECTOS', 'solproy.html'],
		['ADMINISTRACIÓN Y ASEGURAMIENTO','solproy.html'],
		['ANALISIS DE RIESGOS', 'anariesgos.html'],
		['FACTIBILIDAD ECONOMICA', 'anafacti.html'],
		],
		['PROVEEDORES', 'proveedores.html'],
		['PLANIFICACION ESTRATEGICA', 'planes.html'],
		['ANS', 'ans.html'],
		['CLASIFICACION', 'clasific.html'],
		['ACTAS', 'agenda.html'],
		['VACACIONES', 'vacaciones.html'],
		],
		['SOPORTE TECNICO',null,
		['FICHAS TECNICAS', 'ftecnicas.html'],
		['MANTENIMIENTO FUERA', 'manfuera.html'],
		['CRONOGRAMAS', 'cronograma.html'],
		],
		['D&M', 'dim.html'],
		['PRODUCCION - PROAPD',null,
		['PROPIETARIOS Y RESPONSABLES', 'proyrespon.html'],
		['CONTROL TEMP Y HUMEDAD', 'contemhumedad.html'],
		['INVENTARIO DE MEDIOS', 'invmedios.html'],
		['CALENDARIZACION', 'cale.html'],
		],
		['PROBLEMAS- PROAPI',null,
		['PRODUCCION', 'produccion.html'],
		['D&M', 'dym.html'],
		],
		['CONTINGENCIA- PROAPC',null,
		['PLANIFICACION', 'planif.html'],
		['EJECUCION', 'evalu.html'],
		['EVALUACION', 'eval1.html'],
		],
		['SEGURIDAD - PROASI',null,
		['CONTROL Y USUARIOS', 'seguridad.html'],
		['PISTAS DE AUDITORIA', 'cons.html'],
		['INCIDENTES', 'cons.html'],
		],
	],
];