var TREE_ITEMS = [
	['REPORTES',null,
		['ORDENES DE TRABAJO', 'send1.php?menu=orden'],
		['GESTION - PRODAT ',null,
		['CONTRATOS', 'ver_contratos_resumen.php'],
		['PROVEEDORES', 'ver_lista_prov.php'],
		['ANS', 'send1.php?menu=ans'],
		['CLASIFICACION', 'send1.php?menu=clasificacion'],
		['VACACIONES', 'ver_vacaciones.php'],
		],
		
		['SOPORTE TECNICO - PROAST ',null,
		['FICHAS TECNICAS', 'send1.php?menu=fichas'],
		['MANTENIMIENTO FUERA', 'send1.php?menu=manfuera'],
		['CRONOGRAMA', 'ver_calendarizacion.php'],
		],
		
		['PRODUCCION - PROAPD',null,
		['PROPIETARIOS Y RESPONSABLES', 'ver_lista_sistemas.php'],
		['CONTROL TEMP. Y HUMEDAD', 'ver_lista_controltemp.php'],
		['INVENTARIO DE MEDIOS', 'send1.php?menu=invent'],
		['UBICACION DE RESPALDOS', 'send1.php?menu=ubica'],
		['CALENDARIZACION',0,
		['DIARIA', 'ver_lista_diaria.php'],
		['SEMANAL', 'ver_lista_semanal.php'],
		['MENSUAL', 'ver_lista_mensual.php'],
		['TRIMESTRAL', 'ver_lista_trimestral.php'],
		['SEMESTRAL', 'ver_lista_semestral.php'],
		['ANUAL', 'ver_lista_anual.php'],
		],
		],
		
		['CONTINGENCIA - PROAPC ',null,
		['CALENDARIZACION', 'send1.php?menu=calen'],
		],
		
		['SEGURIDAD - PROASI ',null,
		['CONTROL DE USUARIOS', 'send1.php?menu=usuarios'],
		],
		
		['CAMBIOS - PROACP',null,
		['ADMINISTRACION DE FUENTES',null,
		['MODULOS', 'ver_modulos.php'],
		['BACKUPS', 'ver_backups_todos.php'],
		['ARCHIVOS', 'send1.php?menu=archivos'],
		],
		['MAESTRO DE CAMBIOS', 'ver_maestro.php'],
		],
	],
];