var TREE_ITEMS = [
	['ESTADISTICAS',null,
		['ORDENES DE TRABAJO', 'send.php?menu=orden'],
		['GESTION - PRODAT ',null,
		['CONTRATOS', 'send.php?menu=contratos'],
		['PROYECTOS',0,
		['SOLICITUD DE PROYECTOS', 'send.php?menu=solicitud'],
		],
		],
		['PRODUCCION - PROAPD',null,
		['PROPIETARIOS Y RESPONSABLES', 'send.php?menu=propietarios'],
		['CONTROL TEMP Y HUMEDAD', 'send.php?menu=control'],
		],
	],
];