var TREE_ITEMS = [
	['AYUDA', 'MUESTRA.html',
		['INICIO', 'inicio.html'],
		['CARGA', 'Carga.html'],
		['ASIGNACIONES', 'asignaciones.html'],
		['AÑADIR USUARIO',    'ausuario.html'],
		['USUARIO',    'usuarios.html'],
		['ORDENES DE TRABAJO',    'ordtrabajo.html'],
		['GESTION - PRODAT ',null,
		['CONTRATOS', 'contratos.html'],
		['PROYECTOS',0,
		['SOLICITUD DE PROYECTOS', 'solproy.html'],
		['ADMINISTRACIÓN Y ASEGURAMIENTO','admiaseg.htm'],
		['ANALISIS DE RIESGOS', 'anariesgos.html'],
		['FACTIBILIDAD ECONOMICA', 'anafacti.html'],
		],
		['PROVEEDORES', 'proveedores.html'],
		['PLANIFICACION ESTRATEGICA', 'planes.html'],
		['ANS', 'ans.html'],
		['CLASIFICACION', 'clasific.html'],
		['ACTAS', 'actas.html'],
		['VACACIONES', 'vacaciones.html'],
		],
		['SOPORTE TECNICO',null,
		['FICHAS TECNICAS', 'ftecnicas.html'],
		['MANTENIMIENTO FUERA', 'manfuera.html'],
		['CRONOGRAMAS', 'cronograma.html'],
		],
		['D&M', 'dim.html'],
		['PRODUCCION - PROAPD',null,
		['PROPIETARIOS Y RESPONSABLES', 'proyrespon.html'],
		['CONTROL TEMP Y HUMEDAD', 'contemhumedad.html'],
		['INVENTARIO DE MEDIOS', 'invmedios.html'],
		['CALENDARIZACION', 'cale.html'],
		],
		['PROBLEMAS- PROAPI',null,
		['PRODUCCION', 'produccion.html'],
		['D&M', 'dimi.html'],
		],
		['CONTINGENCIA- PROAPC',null,
		['PLANIFICACION', 'planif.html'],
		['EJECUCION', 'evalu.html'],
		['EVALUACION', 'eval1.html'],
		],
		['SEGURIDAD - PROASI',null,
		['CONTROL Y USUARIOS', 'seguridad.html'],
		['PISTAS DE AUDITORIA', 'cons.html'],
		['INCIDENTES', 'cons.html'],
		],
		['CAMBIOS - PROACP ',null,
		['MAESTRO DE CAMBIOS', 'maestro_cambios.html'],
		['ADMINISTRACION DE FUENTES',0,
		['MODULOS', 'modulos.html'],
		['ARCHIVOS','archivos.html'],
		['REPOSITORIO', 'repositorio.html'],
		['COPIA DE TRABAJO', 'copia_trabajo.html'],
		['REPLICA', 'replica.html'],
		['REVISION', 'revision.html'],
		['BACKUPS', 'backups.html'],
		['PISTAS DE AUDITORIA',null,
		['COPIA DE PISTAS DE AUDITORIA', 'pistas_auditoria1.html'],
		['VER PISTAS DE AUDITORIA', 'pistas_auditoria2.html'],
		],
		],
		],
	],
];